# Generated by Django 4.2 on 2024-08-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
    ]
