# Generated by Django 4.2 on 2024-08-07 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_thing'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.thing')),
            ],
        ),
    ]
