# Generated by Django 4.2 on 2024-08-08 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_historybuy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historybuy',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='thing',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='thing',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thing_recommendation', to='api.thing')),
                ('thing_recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.thing')),
            ],
        ),
    ]
