# Generated by Django 4.2 on 2024-08-08 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_historybuy_options_thing_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClientRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_recommendation', to='api.client')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.thing')),
            ],
        ),
    ]
